# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\transUnit_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(550, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 460))
        MainWindow.setMaximumSize(QtCore.QSize(550, 460))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectMethod = QtWidgets.QTabWidget(self.centralwidget)
        self.connectMethod.setGeometry(QtCore.QRect(0, 80, 551, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectMethod.sizePolicy().hasHeightForWidth())
        self.connectMethod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.connectMethod.setFont(font)
        self.connectMethod.setFocusPolicy(QtCore.Qt.TabFocus)
        self.connectMethod.setToolTipDuration(-2)
        self.connectMethod.setStyleSheet("QTabWidget{\n"
"    background-color:transparent;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"   alignment:center;\n"
"}\n"
"QTabWidget::pane{\n"
"    border:3px;\n"
"}\n"
"QTabBar::tab{\n"
"    background-color:transparent;\n"
"    min-width:95px;\n"
"    min-height:40px;\n"
"}\n"
"QTabBar::tab:hover{\n"
"    background:transparent;\n"
"    color:#005BAB;\n"
"}\n"
"QTabBar::tab:selected{\n"
"    border-color: black;\n"
"    background:transparent;\n"
"    color:#005BAB;\n"
"    border-bottom:1px solid #005BAB;\n"
"}")
        self.connectMethod.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.connectMethod.setObjectName("connectMethod")
        self.SSH = QtWidgets.QWidget()
        self.SSH.setObjectName("SSH")
        self.ssh_host = QtWidgets.QLineEdit(self.SSH)
        self.ssh_host.setGeometry(QtCore.QRect(180, 20, 221, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.ssh_host.setFont(font)
        self.ssh_host.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.ssh_host.setText("")
        self.ssh_host.setObjectName("ssh_host")
        self.ssh_username = QtWidgets.QLineEdit(self.SSH)
        self.ssh_username.setGeometry(QtCore.QRect(180, 85, 221, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.ssh_username.setFont(font)
        self.ssh_username.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.ssh_username.setObjectName("ssh_username")
        self.label_4 = QtWidgets.QLabel(self.SSH)
        self.label_4.setGeometry(QtCore.QRect(150, 20, 32, 40))
        self.label_4.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.SSH)
        self.label_5.setGeometry(QtCore.QRect(150, 85, 32, 40))
        self.label_5.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.SSH)
        self.label_6.setGeometry(QtCore.QRect(150, 150, 32, 40))
        self.label_6.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.SSH)
        self.label_7.setGeometry(QtCore.QRect(160, 30, 14, 18))
        self.label_7.setStyleSheet("background:url(img/ip.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.SSH)
        self.label_9.setGeometry(QtCore.QRect(160, 97, 14, 18))
        self.label_9.setStyleSheet("background:url(img/username.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.SSH)
        self.label_10.setGeometry(QtCore.QRect(160, 162, 14, 17))
        self.label_10.setStyleSheet("background:url(img/password.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.ssh_password = QtWidgets.QLineEdit(self.SSH)
        self.ssh_password.setGeometry(QtCore.QRect(180, 150, 221, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.ssh_password.setFont(font)
        self.ssh_password.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.ssh_password.setText("")
        self.ssh_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ssh_password.setObjectName("ssh_password")
        self.ssh_ip_label = QtWidgets.QLabel(self.SSH)
        self.ssh_ip_label.setGeometry(QtCore.QRect(150, 60, 251, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ssh_ip_label.setFont(font)
        self.ssh_ip_label.setStyleSheet("color:red;")
        self.ssh_ip_label.setObjectName("ssh_ip_label")
        self.ssh_username_label = QtWidgets.QLabel(self.SSH)
        self.ssh_username_label.setGeometry(QtCore.QRect(150, 125, 251, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ssh_username_label.setFont(font)
        self.ssh_username_label.setStyleSheet("color:red;")
        self.ssh_username_label.setObjectName("ssh_username_label")
        self.ssh_password_label = QtWidgets.QLabel(self.SSH)
        self.ssh_password_label.setGeometry(QtCore.QRect(150, 190, 251, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ssh_password_label.setFont(font)
        self.ssh_password_label.setStyleSheet("color:red;")
        self.ssh_password_label.setObjectName("ssh_password_label")
        self.connectMethod.addTab(self.SSH, "")
        self.Telnet = QtWidgets.QWidget()
        self.Telnet.setToolTipDuration(-1)
        self.Telnet.setObjectName("Telnet")
        self.label_23 = QtWidgets.QLabel(self.Telnet)
        self.label_23.setGeometry(QtCore.QRect(150, 20, 32, 40))
        self.label_23.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Telnet)
        self.label_24.setGeometry(QtCore.QRect(150, 85, 32, 40))
        self.label_24.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.Telnet)
        self.label_25.setGeometry(QtCore.QRect(150, 150, 32, 40))
        self.label_25.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_38 = QtWidgets.QLabel(self.Telnet)
        self.label_38.setGeometry(QtCore.QRect(160, 30, 14, 18))
        self.label_38.setStyleSheet("background:url(img/ip.png);")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Telnet)
        self.label_39.setGeometry(QtCore.QRect(160, 162, 14, 17))
        self.label_39.setStyleSheet("background:url(img/password.png);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.Telnet)
        self.label_40.setGeometry(QtCore.QRect(160, 97, 14, 18))
        self.label_40.setStyleSheet("background:url(img/username.png);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.telnet_host = QtWidgets.QLineEdit(self.Telnet)
        self.telnet_host.setGeometry(QtCore.QRect(180, 20, 221, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.telnet_host.setFont(font)
        self.telnet_host.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.telnet_host.setText("")
        self.telnet_host.setObjectName("telnet_host")
        self.telnet_username = QtWidgets.QLineEdit(self.Telnet)
        self.telnet_username.setGeometry(QtCore.QRect(180, 85, 221, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.telnet_username.setFont(font)
        self.telnet_username.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.telnet_username.setObjectName("telnet_username")
        self.telnet_password = QtWidgets.QLineEdit(self.Telnet)
        self.telnet_password.setGeometry(QtCore.QRect(180, 150, 221, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.telnet_password.setFont(font)
        self.telnet_password.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.telnet_password.setText("")
        self.telnet_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.telnet_password.setObjectName("telnet_password")
        self.telnet_ip_label = QtWidgets.QLabel(self.Telnet)
        self.telnet_ip_label.setGeometry(QtCore.QRect(150, 60, 251, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.telnet_ip_label.setFont(font)
        self.telnet_ip_label.setStyleSheet("color:red;")
        self.telnet_ip_label.setObjectName("telnet_ip_label")
        self.telnet_username_label = QtWidgets.QLabel(self.Telnet)
        self.telnet_username_label.setGeometry(QtCore.QRect(150, 125, 251, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.telnet_username_label.setFont(font)
        self.telnet_username_label.setStyleSheet("color:red;")
        self.telnet_username_label.setObjectName("telnet_username_label")
        self.telnet_password_label = QtWidgets.QLabel(self.Telnet)
        self.telnet_password_label.setGeometry(QtCore.QRect(150, 190, 251, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.telnet_password_label.setFont(font)
        self.telnet_password_label.setStyleSheet("color:red;")
        self.telnet_password_label.setObjectName("telnet_password_label")
        self.connectMethod.addTab(self.Telnet, "")
        self.ADB = QtWidgets.QWidget()
        self.ADB.setObjectName("ADB")
        self.device_id = QtWidgets.QComboBox(self.ADB)
        self.device_id.setGeometry(QtCore.QRect(120, 20, 201, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.device_id.setFont(font)
        self.device_id.setStyleSheet("QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  right ;\n"
"     width :  20px ;\n"
"      border-left-width :  0px ;\n"
"\n"
"}\n"
" \n"
"QComboBox::down-arrow {\n"
"     image:url(img/arrow.png);\n"
"}")
        self.device_id.setEditable(True)
        self.device_id.setObjectName("device_id")
        self.open_port = QtWidgets.QPushButton(self.ADB)
        self.open_port.setGeometry(QtCore.QRect(330, 86, 101, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.open_port.setFont(font)
        self.open_port.setStyleSheet("QPushButton{\n"
"        text-align:center;\n"
"        color:white;\n"
"        background-color:rgb(0, 91, 171);\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:rgb(24, 91, 171);\n"
"}")
        self.open_port.setObjectName("open_port")
        self.read_devices = QtWidgets.QPushButton(self.ADB)
        self.read_devices.setGeometry(QtCore.QRect(330, 20, 101, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.read_devices.setFont(font)
        self.read_devices.setStyleSheet("QPushButton{\n"
"        text-align:center;\n"
"        color:white;\n"
"        background-color:rgb(0, 91, 171);\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:rgb(24, 91, 171);\n"
"}")
        self.read_devices.setObjectName("read_devices")
        self.adb_port = QtWidgets.QSpinBox(self.ADB)
        self.adb_port.setGeometry(QtCore.QRect(180, 85, 141, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.adb_port.setFont(font)
        self.adb_port.setToolTip("")
        self.adb_port.setStyleSheet("")
        self.adb_port.setMinimum(1024)
        self.adb_port.setMaximum(65535)
        self.adb_port.setProperty("value", 5555)
        self.adb_port.setObjectName("adb_port")
        self.label = QtWidgets.QLabel(self.ADB)
        self.label.setGeometry(QtCore.QRect(120, 100, 13, 13))
        self.label.setStyleSheet("background:url(img/port.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.ADB)
        self.label_2.setGeometry(QtCore.QRect(140, 90, 31, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.device_ip = QtWidgets.QLineEdit(self.ADB)
        self.device_ip.setGeometry(QtCore.QRect(150, 150, 171, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.device_ip.setFont(font)
        self.device_ip.setStyleSheet("border:1px solid black;\n"
"border-left:0px solid white;")
        self.device_ip.setText("")
        self.device_ip.setObjectName("device_ip")
        self.label_26 = QtWidgets.QLabel(self.ADB)
        self.label_26.setGeometry(QtCore.QRect(120, 150, 32, 40))
        self.label_26.setStyleSheet("border:1px solid black;\n"
"border-right:0px solid white;")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_41 = QtWidgets.QLabel(self.ADB)
        self.label_41.setGeometry(QtCore.QRect(130, 160, 14, 18))
        self.label_41.setStyleSheet("background:url(img/ip.png);")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.connect_remote_ip = QtWidgets.QPushButton(self.ADB)
        self.connect_remote_ip.setGeometry(QtCore.QRect(330, 151, 101, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.connect_remote_ip.setFont(font)
        self.connect_remote_ip.setStyleSheet("QPushButton{\n"
"        text-align:center;\n"
"        color:white;\n"
"        background-color:rgb(0, 91, 171);\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:rgb(24, 91, 171);\n"
"}")
        self.connect_remote_ip.setObjectName("connect_remote_ip")
        self.connectMethod.addTab(self.ADB, "")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(150, 356, 252, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("QPushButton{\n"
"        text-align:center;\n"
"        color:white;\n"
"        background-color:rgb(0, 91, 171);\n"
"}\n"
"QPushButton:hover{A\n"
"        background-color:rgb(24, 91, 171);\n"
"}")
        self.loginBtn.setObjectName("loginBtn")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 418, 311, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(140, 140, 140);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 104, 28))
        self.label_3.setStyleSheet("background:url(img/logo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.message = QtWidgets.QLabel(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(260, 20, 31, 30))
        self.message.setStyleSheet("")
        self.message.setText("")
        self.message.setObjectName("message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.connectMethod.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "传输单元服务部署工具"))
        self.connectMethod.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ssh_host.setPlaceholderText(_translate("MainWindow", "请输入传输单元IP地址"))
        self.ssh_username.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.ssh_password.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.ssh_ip_label.setText(_translate("MainWindow", "传输单元IP地址不能为空！"))
        self.ssh_username_label.setText(_translate("MainWindow", "用户名不能为空！"))
        self.ssh_password_label.setText(_translate("MainWindow", "密码不能为空！"))
        self.connectMethod.setTabText(self.connectMethod.indexOf(self.SSH), _translate("MainWindow", "SSH"))
        self.telnet_host.setPlaceholderText(_translate("MainWindow", "请输入传输单元IP地址"))
        self.telnet_username.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.telnet_password.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.telnet_ip_label.setText(_translate("MainWindow", "传输单元IP地址不能为空！"))
        self.telnet_username_label.setText(_translate("MainWindow", "用户名不能为空！"))
        self.telnet_password_label.setText(_translate("MainWindow", "密码不能为空！"))
        self.connectMethod.setTabText(self.connectMethod.indexOf(self.Telnet), _translate("MainWindow", "Telnet"))
        self.open_port.setText(_translate("MainWindow", "开启无线连接"))
        self.read_devices.setText(_translate("MainWindow", "读取设备"))
        self.label_2.setText(_translate("MainWindow", "端口"))
        self.device_ip.setPlaceholderText(_translate("MainWindow", "请输入传输单元IP地址"))
        self.connect_remote_ip.setText(_translate("MainWindow", "无线连接"))
        self.connectMethod.setTabText(self.connectMethod.indexOf(self.ADB), _translate("MainWindow", "ADB"))
        self.loginBtn.setText(_translate("MainWindow", "登录"))
        self.label_8.setText(_translate("MainWindow", "Copyright © 2021 苏州德姆斯信息技术有限公司出品"))
