# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transUnit_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_file(object):
    def setupUi(self, edit_file):
        edit_file.setObjectName("edit_file")
        edit_file.setWindowModality(QtCore.Qt.ApplicationModal)
        edit_file.resize(600, 480)
        edit_file.setMinimumSize(QtCore.QSize(600, 480))
        edit_file.setMaximumSize(QtCore.QSize(600, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        edit_file.setWindowIcon(icon)
        self.save = QtWidgets.QPushButton(edit_file)
        self.save.setGeometry(QtCore.QRect(160, 430, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.save.setFont(font)
        self.save.setStyleSheet("QPushButton{\n"
"        text-align:center;\n"
"        color:white;\n"
"        background-color:rgb(0, 91, 171);\n"
"}\n"
"QPushButton:hover{A\n"
"        background-color:rgb(24, 91, 171);\n"
"}")
        self.save.setObjectName("save")
        self.cancel = QtWidgets.QPushButton(edit_file)
        self.cancel.setGeometry(QtCore.QRect(330, 430, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"        text-align:center;\n"
"        color:rgb(6,6,6);\n"
"}\n"
"QPushButton:hover{A\n"
"        background-color:rgb(24, 91, 171);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.json_edit = QtWidgets.QPlainTextEdit(edit_file)
        self.json_edit.setGeometry(QtCore.QRect(20, 20, 561, 381))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.json_edit.setFont(font)
        self.json_edit.setPlainText("")
        self.json_edit.setObjectName("json_edit")
        self.error_message = QtWidgets.QLabel(edit_file)
        self.error_message.setGeometry(QtCore.QRect(20, 404, 561, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.error_message.setFont(font)
        self.error_message.setStyleSheet("color:red;")
        self.error_message.setObjectName("error_message")

        self.retranslateUi(edit_file)
        QtCore.QMetaObject.connectSlotsByName(edit_file)

    def retranslateUi(self, edit_file):
        _translate = QtCore.QCoreApplication.translate
        edit_file.setWindowTitle(_translate("edit_file", "file_name"))
        self.save.setText(_translate("edit_file", "保存"))
        self.cancel.setText(_translate("edit_file", "取消"))
        self.error_message.setText(_translate("edit_file", "密码不能为空！"))
